name: http_cookie_store
description: Process and store cookies in a cookie store, or directly use it as a http client.
version: 0.0.2
repository: https://github.com/Dampfwalze/http_cookie_store

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  collection: ^1.15.0
  http: ^1.0.0
  quiver: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
